name: create docker image and push to aws ecr

on:
  workflow_dispatch:

env:
  aws_acc_id: ${{ secrets.AWS_ACC_ID }}

jobs:
    build:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./terraform/

      steps:
      - uses: actions/checkout@v2
        name: Check out the repository code
    
      - name: Define environments
        run: |
          docker_image=${{ secrets.AWS_ACC_ID }}.dkr.ecr.us-west-2.amazonaws.com/aca-project-ecr:${{ github.sha }}
          echo "docker_image=$docker_image" >> $GITHUB_ENV
      
      - name: Build Docker image
        working-directory: ./
        run: |
          docker build -t ${{ env.docker_image }} .


      - name: Configure aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-west-2
    
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform configuration
        run: terraform validate

      - name: Plan Terraform changes
        run: terraform apply -target=module.aws-ecr --auto-approve

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: ${{ secrets.AWS_ACC_ID }}

      - name: Docker Push
        run: |
          docker image push ${{ env.docker_image }}

